/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { SaveFeedback$Params } from './fn/feedback/save-feedback';
export { saveFeedback } from './fn/feedback/save-feedback';
export type { GetFeedbacksByBookId$Params } from './fn/feedback/get-feedbacks-by-book-id';
export { getFeedbacksByBookId } from './fn/feedback/get-feedbacks-by-book-id';
export type { UploadBookCoverImage$Params } from './fn/book-controller/upload-book-cover-image';
export { uploadBookCoverImage } from './fn/book-controller/upload-book-cover-image';
export type { RequestBorrowBook$Params } from './fn/book-controller/request-borrow-book';
export { requestBorrowBook } from './fn/book-controller/request-borrow-book';
export type { AddBook$Params } from './fn/book-controller/add-book';
export { addBook } from './fn/book-controller/add-book';
export type { UpdateBookShareableStatus$Params } from './fn/book-controller/update-book-shareable-status';
export { updateBookShareableStatus } from './fn/book-controller/update-book-shareable-status';
export type { UpdateBookArchiveStatus$Params } from './fn/book-controller/update-book-archive-status';
export { updateBookArchiveStatus } from './fn/book-controller/update-book-archive-status';
export type { ReturnBorrowedBook$Params } from './fn/book-controller/return-borrowed-book';
export { returnBorrowedBook } from './fn/book-controller/return-borrowed-book';
export type { ApproveReturnBorrowedBook$Params } from './fn/book-controller/approve-return-borrowed-book';
export { approveReturnBorrowedBook } from './fn/book-controller/approve-return-borrowed-book';
export type { GetAllReturnedBooks$Params } from './fn/book-controller/get-all-returned-books';
export { getAllReturnedBooks } from './fn/book-controller/get-all-returned-books';
export type { GetAllOwnerBooks$Params } from './fn/book-controller/get-all-owner-books';
export { getAllOwnerBooks } from './fn/book-controller/get-all-owner-books';
export type { GetAllBorrowedBooks$Params } from './fn/book-controller/get-all-borrowed-books';
export { getAllBorrowedBooks } from './fn/book-controller/get-all-borrowed-books';
export type { GetBookById$Params } from './fn/book-controller/get-book-by-id';
export { getBookById } from './fn/book-controller/get-book-by-id';
export type { GetAllBooks$Params } from './fn/book-controller/get-all-books';
export { getAllBooks } from './fn/book-controller/get-all-books';
export type { Register$Params } from './fn/authentication/register';
export { register } from './fn/authentication/register';
export type { Authenticate$Params } from './fn/authentication/authenticate';
export { authenticate } from './fn/authentication/authenticate';
export type { ActivateCode$Params } from './fn/authentication/activate-code';
export { activateCode } from './fn/authentication/activate-code';
