/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { BookRequest } from './models/book-request';
export type { FeedbackRequest } from './models/feedback-request';
export type { PageResponseObject } from './models/page-response-object';
export type { RegistrationRequest } from './models/registration-request';
