/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

export interface GetBookById$Params {
  id: number;
}

export function getBookById(
  http: HttpClient,
  rootUrl: string,
  id: GetBookById$Params,
  context?: HttpContext | undefined
): Observable<StrictHttpResponse<{}>> {
  const rb = new RequestBuilder(rootUrl, getBookById.PATH, 'get');

  if (id) {
    // ✅ Use the numeric value instead of the whole object
    rb.path('id', id.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{}>;
    })
  );
}

getBookById.PATH = '/books/get-book/{id}';
