spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  api-docs:
    produces: application/json

server:
  port: 8030
  servlet:
    context-path: /api/v1
