/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addBook } from '../fn/book-controller/add-book';
import { AddBook$Params } from '../fn/book-controller/add-book';
import { approveReturnBorrowedBook } from '../fn/book-controller/approve-return-borrowed-book';
import { ApproveReturnBorrowedBook$Params } from '../fn/book-controller/approve-return-borrowed-book';
import { getAllBooks } from '../fn/book-controller/get-all-books';
import { GetAllBooks$Params } from '../fn/book-controller/get-all-books';
import { getAllBorrowedBooks } from '../fn/book-controller/get-all-borrowed-books';
import { GetAllBorrowedBooks$Params } from '../fn/book-controller/get-all-borrowed-books';
import { getAllOwnerBooks } from '../fn/book-controller/get-all-owner-books';
import { GetAllOwnerBooks$Params } from '../fn/book-controller/get-all-owner-books';
import { getAllReturnedBooks } from '../fn/book-controller/get-all-returned-books';
import { GetAllReturnedBooks$Params } from '../fn/book-controller/get-all-returned-books';
import { getBookById } from '../fn/book-controller/get-book-by-id';
import { GetBookById$Params } from '../fn/book-controller/get-book-by-id';
import { PageResponseBookResponse } from '../models/page-response-book-response';
import { PageResponseBorrowedBookResponse } from '../models/page-response-borrowed-book-response';
import { requestBorrowBook } from '../fn/book-controller/request-borrow-book';
import { RequestBorrowBook$Params } from '../fn/book-controller/request-borrow-book';
import { returnBorrowedBook } from '../fn/book-controller/return-borrowed-book';
import { ReturnBorrowedBook$Params } from '../fn/book-controller/return-borrowed-book';
import { updateBookArchiveStatus } from '../fn/book-controller/update-book-archive-status';
import { UpdateBookArchiveStatus$Params } from '../fn/book-controller/update-book-archive-status';
import { updateBookShareableStatus } from '../fn/book-controller/update-book-shareable-status';
import { UpdateBookShareableStatus$Params } from '../fn/book-controller/update-book-shareable-status';
import { uploadBookCoverImage } from '../fn/book-controller/upload-book-cover-image';
import { UploadBookCoverImage$Params } from '../fn/book-controller/upload-book-cover-image';


/**
 * APIs for managing books in the Book Station application
 */
@Injectable({ providedIn: 'root' })
export class BookControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `uploadBookCoverImage()` */
  static readonly UploadBookCoverImagePath = '/books/upload-cover-image/{bookId}';

  uploadBookCoverImage$Response(
    params: { 'book-id': number; body: FormData; bookId: number },
    context?: HttpContext | undefined
  ): Observable<StrictHttpResponse<{}>> {
    return uploadBookCoverImage(this.http, this.rootUrl, params, context);
  }

  uploadCoverManual(bookId: number, file: File) {
    const formData = new FormData();
    formData.append('image', file);

    return this.http.post(
      `${this.rootUrl}/books/upload-cover-image/${bookId}`,
      formData
    );
  }

  /** Path part for operation `requestBorrowBook()` */
  static readonly RequestBorrowBookPath = '/books/request-borrow-book/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `requestBorrowBook()` instead.
   *
   * This method doesn't expect any request body.
   */
  requestBorrowBook$Response(
    params: RequestBorrowBook$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<{}>> {
    return requestBorrowBook(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `requestBorrowBook$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  requestBorrowBook(
    params: RequestBorrowBook$Params,
    context?: HttpContext
  ): Observable<{}> {
    return this.requestBorrowBook$Response(params, context).pipe(
      map((r: StrictHttpResponse<{}>): {} => r.body)
    );
  }

  /** Path part for operation `addBook()` */
  static readonly AddBookPath = '/books/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addBook()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addBook$Response(
    params: AddBook$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<{}>> {
    return addBook(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addBook$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   *
   * ✅ We assume backend returns the new book ID (number)
   */
  addBook(
    params: AddBook$Params,
    context?: HttpContext
  ): Observable<number> {
    return this.addBook$Response(params, context).pipe(
      map((r: StrictHttpResponse<{}>): number => r.body as number)
    );
  }

  /** Path part for operation `updateBookShareableStatus()` */
  static readonly UpdateBookShareableStatusPath = '/books/update-sharable-book/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateBookShareableStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateBookShareableStatus$Response(
    params: UpdateBookShareableStatus$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<{}>> {
    return updateBookShareableStatus(this.http, this.rootUrl, params, context);
  }

  updateBookShareableStatus(
    params: UpdateBookShareableStatus$Params,
    context?: HttpContext
  ): Observable<{}> {
    return this.updateBookShareableStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<{}>): {} => r.body)
    );
  }

  /** Path part for operation `updateBookArchiveStatus()` */
  static readonly UpdateBookArchiveStatusPath = '/books/update-archive-book/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateBookArchiveStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateBookArchiveStatus$Response(
    params: UpdateBookArchiveStatus$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<{}>> {
    return updateBookArchiveStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateBookArchiveStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateBookArchiveStatus(
    params: UpdateBookArchiveStatus$Params,
    context?: HttpContext
  ): Observable<{}> {
    return this.updateBookArchiveStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<{}>): {} => r.body)
    );
  }

  /** Path part for operation `returnBorrowedBook()` */
  static readonly ReturnBorrowedBookPath = '/books/return-book/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `returnBorrowedBook()` instead.
   *
   * This method doesn't expect any request body.
   */
  returnBorrowedBook$Response(
    params: ReturnBorrowedBook$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<{}>> {
    return returnBorrowedBook(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `returnBorrowedBook$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  returnBorrowedBook(
    params: ReturnBorrowedBook$Params,
    context?: HttpContext
  ): Observable<{}> {
    return this.returnBorrowedBook$Response(params, context).pipe(
      map((r: StrictHttpResponse<{}>): {} => r.body)
    );
  }

  /** Path part for operation `approveReturnBorrowedBook()` */
  static readonly ApproveReturnBorrowedBookPath = '/books/approve-return-book/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `approveReturnBorrowedBook()` instead.
   *
   * This method doesn't expect any request body.
   */
  approveReturnBorrowedBook$Response(
    params: ApproveReturnBorrowedBook$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<{}>> {
    return approveReturnBorrowedBook(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `approveReturnBorrowedBook$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  approveReturnBorrowedBook(
    params: ApproveReturnBorrowedBook$Params,
    context?: HttpContext
  ): Observable<{}> {
    return this.approveReturnBorrowedBook$Response(params, context).pipe(
      map((r: StrictHttpResponse<{}>): {} => r.body)
    );
  }

  /** Path part for operation `getAllReturnedBooks()` */
  static readonly GetAllReturnedBooksPath = '/books/get-returned-books';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllReturnedBooks()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllReturnedBooks$Response(
    params?: GetAllReturnedBooks$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<PageResponseBorrowedBookResponse>> {
    return getAllReturnedBooks(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllReturnedBooks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllReturnedBooks(
    params?: GetAllReturnedBooks$Params,
    context?: HttpContext
  ): Observable<PageResponseBorrowedBookResponse> {
    return this.getAllReturnedBooks$Response(params, context).pipe(
      map(
        (r: StrictHttpResponse<PageResponseBorrowedBookResponse>): PageResponseBorrowedBookResponse =>
          r.body
      )
    );
  }

  /** Path part for operation `getAllOwnerBooks()` */
  static readonly GetAllOwnerBooksPath = '/books/get-owner-books';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllOwnerBooks()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllOwnerBooks$Response(
    params?: GetAllOwnerBooks$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<PageResponseBookResponse>> {
    return getAllOwnerBooks(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllOwnerBooks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllOwnerBooks(
    params?: GetAllOwnerBooks$Params,
    context?: HttpContext
  ): Observable<PageResponseBookResponse> {
    return this.getAllOwnerBooks$Response(params, context).pipe(
      map(
        (r: StrictHttpResponse<PageResponseBookResponse>): PageResponseBookResponse =>
          r.body
      )
    );
  }

  /** Path part for operation `getAllBorrowedBooks()` */
  static readonly GetAllBorrowedBooksPath = '/books/get-borrowed-books';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllBorrowedBooks()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllBorrowedBooks$Response(
    params?: GetAllBorrowedBooks$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<PageResponseBorrowedBookResponse>> {
    return getAllBorrowedBooks(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllBorrowedBooks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllBorrowedBooks(
    params?: GetAllBorrowedBooks$Params,
    context?: HttpContext
  ): Observable<PageResponseBorrowedBookResponse> {
    return this.getAllBorrowedBooks$Response(params, context).pipe(
      map(
        (r: StrictHttpResponse<PageResponseBorrowedBookResponse>): PageResponseBorrowedBookResponse =>
          r.body
      )
    );
  }

  /** Path part for operation `getBookById()` */
  static readonly GetBookByIdPath = '/books/get-book/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getBookById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBookById$Response(
    params: GetBookById$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<{}>> {
    return getBookById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getBookById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBookById(
    params: GetBookById$Params,
    context?: HttpContext
  ): Observable<{}> {
    return this.getBookById$Response(params, context).pipe(
      map((r: StrictHttpResponse<{}>): {} => r.body)
    );
  }

  /** Path part for operation `getAllBooks()` */
  static readonly GetAllBooksPath = '/books/get-all-books';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllBooks()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllBooks$Response(
    params?: GetAllBooks$Params,
    context?: HttpContext
  ): Observable<StrictHttpResponse<PageResponseBookResponse>> {
    return getAllBooks(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllBooks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllBooks(
    params?: GetAllBooks$Params,
    context?: HttpContext
  ): Observable<PageResponseBookResponse> {
    return this.getAllBooks$Response(params, context).pipe(
      map(
        (r: StrictHttpResponse<PageResponseBookResponse>): PageResponseBookResponse =>
          r.body
      )
    );
  }
}
