/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getFeedbacksByBookId } from '../fn/feedback/get-feedbacks-by-book-id';
import { GetFeedbacksByBookId$Params } from '../fn/feedback/get-feedbacks-by-book-id';
import { PageResponseObject } from '../models/page-response-object';
import { saveFeedback } from '../fn/feedback/save-feedback';
import { SaveFeedback$Params } from '../fn/feedback/save-feedback';

@Injectable({ providedIn: 'root' })
export class FeedbackService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `saveFeedback()` */
  static readonly SaveFeedbackPath = '/feedbacks/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveFeedback()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveFeedback$Response(params: SaveFeedback$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return saveFeedback(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveFeedback$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveFeedback(params: SaveFeedback$Params, context?: HttpContext): Observable<{
}> {
    return this.saveFeedback$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getFeedbacksByBookId()` */
  static readonly GetFeedbacksByBookIdPath = '/feedbacks/book/{bookId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFeedbacksByBookId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFeedbacksByBookId$Response(params: GetFeedbacksByBookId$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseObject>> {
    return getFeedbacksByBookId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFeedbacksByBookId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFeedbacksByBookId(params: GetFeedbacksByBookId$Params, context?: HttpContext): Observable<PageResponseObject> {
    return this.getFeedbacksByBookId$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseObject>): PageResponseObject => r.body)
    );
  }

}
